### ISSUE TITLE
Key error for unused in variable

### ISSUE THREAD

**Issue by handras** [moderngl/moderngl#347] opened 2019-09-25 17:32 UTC
**Description**

This issue is similar to #149.
I started out from the moderngl_window and moderngl examples.
I removed the usage of  `in_color` variable in the vertex shader.
After this the program throws a KeyError:

```
self.vao = self.ctx.simple_vertex_array(self.prog, vbo, 'in_vert', 'in_color')
  File "D:\Miniconda3\envs\shader\lib\site-packages\moderngl\context.py", line 772, in simple_vertex_array
    content = [(buffer, detect_format(program, attributes)) + attributes]
  File "D:\Miniconda3\envs\shader\lib\site-packages\moderngl\program.py", line 135, in detect_format
    return ' '.join('%d%s' % fmt(program[a]) for a in attributes)
  File "D:\Miniconda3\envs\shader\lib\site-packages\moderngl\program.py", line 135, in <genexpr>
    return ' '.join('%d%s' % fmt(program[a]) for a in attributes)
  File "D:\Miniconda3\envs\shader\lib\site-packages\moderngl\program.py", line 43, in __getitem__
    return self._members[key]
KeyError: 'in_color'
```

**Proof of code**

```py
import logging
import os
import moderngl_window as mglw
import numpy as np

class Example(mglw.WindowConfig):
    gl_version = (3, 3)
    title = "ModernGL Example"
    window_size = (1280, 720)
    aspect_ratio = 16 / 9
    resizable = True
    samples = 4
    log_level = logging.DEBUG

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.prog = self.ctx.program(
            vertex_shader='''
       #version 330
        
        in vec2 in_vert;
        in vec3 in_color;

        void main() {
            gl_Position = vec4(in_vert, 0.0, 1.0);
        }
    ''',
            fragment_shader='''
        #version 330

        out vec3 f_color;

        void main() {
            f_color = vec3(1.0, 0.0, 1.0);
        }
    ''', )

        x = np.linspace(-1.0, 1.0, 50)
        y = np.random.rand(50) - 0.5
        r = np.random.rand(50)
        g = np.zeros(50)
        b = np.random.rand(50)

        vertices = np.dstack([x, y, r, g, b])

        vbo = self.ctx.buffer(vertices.astype('f4').tobytes())
        self.vao = self.ctx.simple_vertex_array(self.prog, vbo, 'in_vert', 'in_color')

    def render(self, time, frametime):
        # This method is called every frame
        self.vao.render()

    @classmethod
    def run(cls):
        mglw.run_window_config(cls)


if __name__ == '__main__':
    Example.run()
```

**Expected behavior**

The program runs without error and displays magenta triangles.

**Version info**

```
moderngl 5.5.3
--------------
vendor: NVIDIA Corporation
renderer: GeForce GTX 950M/PCIe/SSE2
version: 4.6.0 NVIDIA 390.77
python: 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
platform: win32
code: 460
```

**Comment by einarf** [comment] 2019-09-25 17:47
The `in_color` attribute in your vertex shader is not used for anything and is then removed in the program compile and link steps. Just remove it from your shader and don't referencd the name when creating the vertexarray.

GLSL will purge away anything not actively used in a program. Attributes, uniforms etc

**Comment by handras** [comment] 2019-09-25 18:19
I was aware of the fact that the variable is unused. It get purged even if the vertex shader passes it to the fragment shader in which it don't get used.

However I am trying to mimic the behavior of Shadertoy and play with shaders. I think it frequently happens during the development process that a variable temporarily becamos unused. It is certainly the case with uniforms like time and cursor position.

This is why I'd like to leave "unused" variables in the shader programs.

**Comment by einarf** [comment] 2019-09-25 20:13
If you want automatic attribute mapping you can use the `VAO` wrapper in moderngl_window:
https://moderngl-window.readthedocs.io/en/latest/reference/opengl/vao.html

It's basically just a collection of buffers with the ability to adapt to a program matching the attributes or a subset of the attributes (it calculates padding etc).

```python
vao = VAO(name="something", mode=moderngl.TRIANGLES)
vao.buffer(vertices.astype('f4').tobytes(), '2f 3f', ['in_vert', 'in_color'])

# VertexBuffers are created on the fly and cached internally adapting to any
# program that has compatible attribute format and name
vao.render(self.prog)
```

For setting uniforms you just have to query for their existence just like plain opengl or catch the raised keyerror when accessing them. That part if fairly simple to solve.
https://moderngl.readthedocs.io/en/stable/reference/program.html#moderngl.Program.get
or try/catch around `self.prog['uniform_name']`

**Comment by handras** [comment] 2019-09-26 18:09
Thank you for the tips! After all it may not be a bug.

**Comment by einarf** [comment] 2019-09-26 18:22
It's definitly not a bug in moderngl 5.x. What matters under the hood is the introspected values from the shader program. There have been suggestions in the past supporting optional attributes during vertexarray creation, but this is a problem we can solve in python.

vertexarrays will change quite a bit in moderngl 6.

**Comment by einarf** [comment] 2019-09-30 16:14
Closing this one. Be free to re-open if needed.

**Closed by einarf** 2019-09-30 16:14 UTC
