### ISSUE TITLE
Wayland: Context creation failed

### ISSUE THREAD

**Issue by istvan-szollosi** [moderngl/moderngl#508] opened 2022-06-08 10:31 UTC
Upgrading from moderngl 5.5.3 to 5.6.4

```
Traceback (most recent call last):
  File "/home/istvan/Work/Mollia/mollia_window_linux/test_main_window_mouse.py", line 7, in <module>
    ctx = mgl.create_context()
  File "/home/istvan/.local/lib/python3.10/site-packages/moderngl/context.py", line 1619, in create_context
    ctx.mglo, ctx.version_code = mgl.create_context(glversion=require, mode=mode, **settings)
  File "/home/istvan/.local/lib/python3.10/site-packages/glcontext/__init__.py", line 93, in create
    return x11.create_context(**kwargs)
Exception: (detect) glXGetCurrentContext: cannot detect OpenGL context
```

```
Linux fedora 5.17.12-300.fc36.x86_64 #1 SMP PREEMPT Mon May 30 16:56:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by einarf** [comment] 2022-06-08 10:35
A difference from moderngl 5.5 and 5.6 is that we are no longer statically linking libGL.so. Can this be related?

**Comment by szabolcsdombi** [comment] 2022-06-08 10:38
there were no calls into `glcontext` so `5.5.3` does the context creation is in the moderngl code.

**Comment by szabolcsdombi** [comment] 2022-06-08 10:39
also the latest glcontext fails to create the context for the window
but succeeds with the 'standalone' variant

**Comment by istvan-szollosi** [comment] 2022-06-08 11:57
UPDATE: The problem seems to be Wayland related. No crash on X11 session.

**Comment by jimy-byerley** [comment] 2024-01-19 21:16
Any news on this ?
I get the same error on debian 12 using wayland, and likewise no problem using Xorg 
(of course xorg tends to be deprecated so I would like not to use it)

**Comment by szabolcsdombi** [comment] 2024-01-20 09:07
Use backend="egl" for now. Hopefully this will be soon the default anyways

**Comment by szabolcsdombi** [comment] 2024-01-21 20:21
https://github.com/moderngl/moderngl/issues/650

**Comment by szabolcsdombi** [comment] 2024-01-31 20:37
update to moderngl 5.10.0 and a simple `moderngl.create_context()` or `moderngl.get_context()` without parameter should work. Please choose `moderngl.get_context()` even if both working.

**Comment by jimy-byerley** [comment] 2024-02-03 11:33
Hum ... but `moderngl.create_context()` was what I did before, and I still get the issue decribed in the initial post of the thread even with moderngl 5.10.
I just tries `moderngl.get_context()` and got a different error
```python
  File "/home/jimy/.local/lib/python3.11/site-packages/madcad/rendering.py", line 552, in render
    with self.ctx:
  File "/home/jimy/.local/lib/python3.11/site-packages/moderngl/__init__.py", line 1913, in __enter__
    self.mglo.__enter__()
AttributeError: 'DefaultLoader' object has no attribute '__enter__'. Did you mean: '__ne__'?
```
I need find what changed in moderngl 5.10 about context management

**Comment by szabolcsdombi** [comment] 2024-02-03 12:56
> I need find what changed in moderngl 5.10 about context management

- ModernGL 5.9 uses only the glcontext opengl context detection
- ModernGL 5.10 adds a new way to detect opengl contexts better, this is only available in get_context
- ModernGL 6.x will only use the new way by default.

This is only what changed regarding the context management.

The new way we detect opengl contexts is trying for egl and falls back for x11.
I reopen the issue until we fix it for your case.

**Comment by szabolcsdombi** [comment] 2024-02-03 12:58
By mistake the `with self.ctx:` is broken at the moment, will fix that a bit later.

**Comment by szabolcsdombi** [comment] 2024-02-03 13:04
https://github.com/moderngl/moderngl/issues/660

**Comment by szabolcsdombi** [comment] 2024-02-03 13:05
@jimy-byerley Please install moderngl from the main branch.
version should be 6.0.0 however it is not yet released.

Please confirm if it it working or not.

**Comment by jimy-byerley** [comment] 2024-02-03 13:18
I will try it
Here is a minimal example to reproduce the issue by the way
```python
from PyQt5.QtWidgets import QOpenGLWidget, QApplication
from PyQt5.QtGui import QSurfaceFormat
from PyQt5.QtCore import Qt
import numpy as np
import moderngl as mgl

opengl_version = (3,3)

class View(QOpenGLWidget):
	def __init__(self, parent=None):
		# super init
		super(QOpenGLWidget, self).__init__(parent)
		fmt = QSurfaceFormat()
		fmt.setVersion(*opengl_version)
		fmt.setProfile(QSurfaceFormat.CoreProfile)
		fmt.setSamples(4)
		self.setFormat(fmt)		
		self.ctx = None

	def initializeGL(self):
		self.ctx = mgl.get_context()

		# self.fb_screen is already created and sized by Qt
		self.fb = self.ctx.detect_framebuffer(self.defaultFramebufferObject())
		self.prog = self.ctx.program(
			vertex_shader='''
				#version 330

				in vec2 in_vert;

				void main() {
					gl_Position = vec4(in_vert, 0.0, 1.0);
				}
			''',
			fragment_shader='''
				#version 330

				out vec4 f_color;

				void main() {
					f_color = vec4(0.3, 0.5, 1.0, 1.0);
				}
			''',
		)

		vertices = np.array([
			0.0, 0.8,
			-0.6, -0.8,
			0.6, -0.8,
		], dtype='f4')

		self.vbo = self.ctx.buffer(vertices)
		self.vao = self.ctx.simple_vertex_array(self.prog, self.vbo, 'in_vert')

	def paintGL(self):
		self.makeCurrent()
		with self.ctx:
			self.fb.use()
			self.ctx.clear(1.0, 1.0, 1.0)
			self.vao.render()

	

import sys
QApplication.setAttribute(Qt.AA_ShareOpenGLContexts, True)
app = QApplication(sys.argv)
view = View()
view.show()
app.exec()
```

**Comment by jimy-byerley** [comment] 2024-02-03 13:24
just tested it: version 6.0 from the main branch (commit e175d069a13fd7bbc38e34fb8cfce447d91e0ff5)
works on wayland !

I have errors on some buffer creation I did not had before, meaning moderngl 6 is less forgiving than 5, anyway I will easily fix that:
```python
  File "/home/jimy/.local/lib/python3.11/site-packages/madcad/displays.py", line 389, in __init__
    self.vb_faces = scene.ctx.buffer(np.array(faces, 'u4', copy=False))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jimy/.local/lib/python3.11/site-packages/moderngl/__init__.py", line 1538, in buffer
    res.mglo, res._size, res._glo = self.mglo.buffer(data, reserve, dynamic)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: ndarray is not C-contiguous
```

**Comment by jimy-byerley** [comment] 2024-02-03 13:32
Out of interested curiosity: when do you plan to release moderngl 6.0 ?

**Comment by szabolcsdombi** [comment] 2024-02-03 14:44
> `ValueError: ndarray is not C-contiguous`

I will add an issue for this, I already solved this for zengl, basically `C-contiguous` is not required.
When not provided a copy is created temporarily, it is up to the user to provide contig memory to avoid the copy. It is fast anyways.

**Comment by szabolcsdombi** [comment] 2024-02-03 14:51
added https://github.com/moderngl/moderngl/issues/661
closing this as it is working.

I can release `6.0.0a1` or `6.0.0.dev1` anytime.
For `6.x` i still have some non-backward compatible changes to do.
Simple ones, but important.

Basically 6.x will be still very backward compatible, some parts are not the best at the moment and can be fixed without breaking most users' code at all. I just want 6.x for that.

Please let me know if you need alpha/dev versions installable from pypi.

**Closed** 2024-02-03 14:52 UTC

**Comment by jimy-byerley** [comment] 2024-02-03 22:56
For the moment, I think using the main branch of moderngl is fine. I will tell the madcad users to do so as well if they need to run on wayland. 
Anyway, since moderngl 6 is a major, I will only bump the minimum moderngl required in my projects when you will have introduced the breaking changes.

Thanks for having fixed this and for the quick answers !
