### ISSUE TITLE
Error "Requested OpenGL version 330, got version 0"

### ISSUE THREAD

**Issue by OlaKenji** [moderngl/moderngl#581] opened 2023-04-29 09:33 UTC
*Description*
I am trying to incooporate moderngl into my pygame project. Below is an example code:

import pygame
import moderngl
pygame.init()
screen = pygame.display.set_mode((800, 600), pygame.OPENGL | pygame.DOUBLEBUF)
ctx = moderngl.create_context()
.
.
.

Running the code gives
pygame-ce 2.2.0 (SDL 2.0.22, Python 3.9.12)
Traceback (most recent call last):
line 11, in <module>
    ctx = moderngl.create_context()
line 2182, in create_context
    raise ValueError('Requested OpenGL version {0}, got version {1}'.format(
ValueError: Requested OpenGL version 330, got version 0

It seems the version of the OpenGL installed is not recognised? Could it perhaps be hardware related issue?

*Version info*
$python -m moderngl
moderngl 5.8.2
--------------
vendor: Apple
renderer: Apple M1 Pro
version: 4.1 Metal - 76.3
python: 3.9.12 (main, Apr  5 2022, 01:53:17) 
[Clang 12.0.0 ]
platform: darwin
code: 410

**Comment by einarf** [comment] 2023-04-29 11:46
You need to set the right context flags: https://github.com/moderngl/moderngl-window/blob/515979442dbbacf5bf40821e1ac95ed745982c2e/moderngl_window/context/pygame2/window.py#L30-L53

Mac only accepts forward compatible core contexts. This should work on all platforms.

**Comment by OlaKenji** [comment] 2023-04-29 12:34
Thank you for your answer. But aren't the required flags (pygame.OPENGL | pygame.DOUBLEBUF) set when the display is initialised via screen = pygame.display.set_mode((800, 600), pygame.OPENGL | pygame.DOUBLEBUF)?

**Comment by einarf** [comment] 2023-04-29 20:33
Closing this for now. Be free to add comments if the problem is not resolved.

**Closed by einarf** 2023-04-29 20:33 UTC
