### ISSUE TITLE
M1 Mac - Guide Code Printing All Zeros

### ISSUE THREAD

**Issue by BenWeisz** [moderngl/moderngl#493] opened 2022-02-22 05:29 UTC
**Description**

Running code block from [guide](https://moderngl.readthedocs.io/en/latest/the_guide/basic.html#vertex-shader-transforms) on M1 macbook air outputs all zeros for value, and product pairs

**Proof of code**

Please see [guide](https://moderngl.readthedocs.io/en/latest/the_guide/basic.html#vertex-shader-transforms).

**Expected behavior**

Expected output as per guide:
```
value = 0.0, product = 0.0
value = 1.0, product = 1.0
value = 2.0, product = 4.0
value = 3.0, product = 9.0
value = 4.0, product = 16.0
value = 5.0, product = 25.0
value = 6.0, product = 36.0
value = 7.0, product = 49.0
value = 8.0, product = 64.0
value = 9.0, product = 81.0
```

**Version info**

Running on MacOS Monterey 12.0.1

```
moderngl 5.6.4
--------------
vendor: Apple
renderer: Apple M1
version: 4.1 Metal - 76.1
python: 3.9.10 (main, Jan 15 2022, 11:40:53) 
[Clang 13.0.0 (clang-1300.0.29.3)]
platform: darwin
code: 410
```

**Comment by einarf** [comment] 2022-02-28 23:59
Weird. Does it work if you reduce it to one out varying? I'm really puzzled what causes this. There are other issues as well related to interlaved buffers with integer values.

**Comment by TheMartianObserver** [comment] 2022-03-09 04:44
FWIW, having the same problem on an Intel Macbook Pro (13-inch, 2020) with the integrated Intel Iris. However, the very similar example from the repo `transform_feedback_gen_buffer.py` works. Headless mode causing issues?

**Comment by einarf** [comment] 2022-03-09 14:31
It would be nice to know if `ctx.error` contains anything. There might be some weird limitations with  apple drivers here. They have not been eager to maintain them since 2018 due to deprecation. Still there might be things that can be done to make it work.

**Comment by BenWeisz** [comment] 2022-03-10 03:11
Unfortunately I'm kinda busy with school right now but I can get the `ctx.error` for you / try to investigate this one later next month. 

Are there any good resources on how to compile the project in debug mode and attach a debugger for this project?

**Comment by einarf** [comment] 2022-03-10 11:02
Just a `print(ctx.error)` is a good start.

**Comment by einarf** [comment] 2022-03-11 19:34
I think I know what the problem is now. I am guessing the mac drivers don't support rendering with no buffer input. I should probably rewrite the example to be more compatible.

**Comment by BenWeisz** [comment] 2022-03-18 04:15
I'm not sure if this helps at this point but `ctx.error` prints `GL_INVALID_FRAMEBUFFER_OPERATION`

**Comment by einarf** [comment] 2022-03-18 04:17
That smells like the shader is wanting inputs. I think that should solve it all.

**Comment by szabolcsdombi** [comment] 2022-03-19 14:49
it happens because the vao.transform sets a `gl_invalid_framebuffer_operation`.
indeed adding a fbo = ... fbo.use() before it resolves the problem.
this can be fixed in moderngl because the default standalone context creates a framebuffer to avoid this issue. it seems it is not working on m1 with the current setup so it has to be changed.
I fix it soon.

**Comment by BenWeisz** [comment] 2022-03-19 20:02
Koszi!

**Comment by szabolcsdombi** [comment] 2022-03-20 08:26
https://github.com/moderngl/moderngl/commit/7dfb1606e7d6a78b31f6ff1df7e65af953d92a14

this should fix the issue. we will release this soon.

**Comment by AlasdairMott** [comment] 2022-08-06 23:57
I had the same issue, 2019 intel MacBook. Adding this to the example fixed the issue:
```py
fbo = ctx.simple_framebuffer((512, 512))
fbo.use()
fbo.clear(0.0, 0.0, 0.0, 1.0)
```
I'm not sure whether clearing the frame buffer is necessary though.

**Comment by einarf** [comment] 2022-08-08 16:05
In 5.6.x you just need a framebuffer bound on mac. It's likely a bug in their drivers.

**Comment by szabolcsdombi** [comment] 2023-02-24 19:08
this was fixed, on context creation for osx a dummy framebuffer is created and boud in the place of fbo=0 that is invalid.

**Closed by szabolcsdombi** 2023-02-24 19:08 UTC
